//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFilterTextReader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageConsts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageConsts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFilterTextReader.Localization.LanguageConsts", typeof(LanguageConsts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather time modified.
        /// </summary>
        internal static string _0B63E350_9CCC_11D0_BCDB_00805FCCCE04_4 {
            get {
                return ResourceManager.GetString("_0B63E350_9CCC_11D0_BCDB_00805FCCCE04_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document format.
        /// </summary>
        internal static string _0B63E350_9CCC_11D0_BCDB_00805FCCCE04_5 {
            get {
                return ResourceManager.GetString("_0B63E350_9CCC_11D0_BCDB_00805FCCCE04_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera manufacturer.
        /// </summary>
        internal static string _14B81DA1_0135_4D31_96D9_6CBFC9671A99_271 {
            get {
                return ResourceManager.GetString("_14B81DA1_0135_4D31_96D9_6CBFC9671A99_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera model.
        /// </summary>
        internal static string _14B81DA1_0135_4D31_96D9_6CBFC9671A99_272 {
            get {
                return ResourceManager.GetString("_14B81DA1_0135_4D31_96D9_6CBFC9671A99_272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo orientation.
        /// </summary>
        internal static string _14B81DA1_0135_4D31_96D9_6CBFC9671A99_274 {
            get {
                return ResourceManager.GetString("_14B81DA1_0135_4D31_96D9_6CBFC9671A99_274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string _49691C90_7E17_101A_A91C_08002B2ECDA9_9 {
            get {
                return ResourceManager.GetString("_49691C90_7E17_101A_A91C_08002B2ECDA9_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music genre.
        /// </summary>
        internal static string _56A3372E_CE9C_11D2_9F0E_006097C686F6_11 {
            get {
                return ResourceManager.GetString("_56A3372E_CE9C_11D2_9F0E_006097C686F6_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music artist.
        /// </summary>
        internal static string _56A3372E_CE9C_11D2_9F0E_006097C686F6_2 {
            get {
                return ResourceManager.GetString("_56A3372E_CE9C_11D2_9F0E_006097C686F6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music album.
        /// </summary>
        internal static string _56A3372E_CE9C_11D2_9F0E_006097C686F6_4 {
            get {
                return ResourceManager.GetString("_56A3372E_CE9C_11D2_9F0E_006097C686F6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music year.
        /// </summary>
        internal static string _56A3372E_CE9C_11D2_9F0E_006097C686F6_5 {
            get {
                return ResourceManager.GetString("_56A3372E_CE9C_11D2_9F0E_006097C686F6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music track.
        /// </summary>
        internal static string _56A3372E_CE9C_11D2_9F0E_006097C686F6_7 {
            get {
                return ResourceManager.GetString("_56A3372E_CE9C_11D2_9F0E_006097C686F6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio time length.
        /// </summary>
        internal static string _56A3372E_CE9C_11D2_9F0E_006097C686F6_8 {
            get {
                return ResourceManager.GetString("_56A3372E_CE9C_11D2_9F0E_006097C686F6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image demensions.
        /// </summary>
        internal static string _6444048F_4C8B_11D1_8B70_080036B11A03_13 {
            get {
                return ResourceManager.GetString("_6444048F_4C8B_11D1_8B70_080036B11A03_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image X resolution.
        /// </summary>
        internal static string _6444048F_4C8B_11D1_8B70_080036B11A03_5 {
            get {
                return ResourceManager.GetString("_6444048F_4C8B_11D1_8B70_080036B11A03_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Y resulution.
        /// </summary>
        internal static string _6444048F_4C8B_11D1_8B70_080036B11A03_6 {
            get {
                return ResourceManager.GetString("_6444048F_4C8B_11D1_8B70_080036B11A03_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio average data rate.
        /// </summary>
        internal static string _64440490_4C8B_11D1_8B70_080036B11A03_4 {
            get {
                return ResourceManager.GetString("_64440490_4C8B_11D1_8B70_080036B11A03_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video frame width.
        /// </summary>
        internal static string _64440491_4C8B_11D1_8B70_080036B11A03_3 {
            get {
                return ResourceManager.GetString("_64440491_4C8B_11D1_8B70_080036B11A03_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video frame height.
        /// </summary>
        internal static string _64440491_4C8B_11D1_8B70_080036B11A03_4 {
            get {
                return ResourceManager.GetString("_64440491_4C8B_11D1_8B70_080036B11A03_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video frame rate.
        /// </summary>
        internal static string _64440491_4C8B_11D1_8B70_080036B11A03_6 {
            get {
                return ResourceManager.GetString("_64440491_4C8B_11D1_8B70_080036B11A03_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_class {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_component {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_const {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_def {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_delegate {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_enum {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_event {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_field {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_func {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_func", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_interface {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_project {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_property {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_solution {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct.
        /// </summary>
        internal static string _8DEE0300_16C2_101B_B121_08002B2ECDA9_struct {
            get {
                return ResourceManager.GetString("_8DEE0300_16C2_101B_B121_08002B2ECDA9_struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string _B725F130_47EF_101A_A5F1_02608C9EEBAC_10 {
            get {
                return ResourceManager.GetString("_B725F130_47EF_101A_A5F1_02608C9EEBAC_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string _B725F130_47EF_101A_A5F1_02608C9EEBAC_12 {
            get {
                return ResourceManager.GetString("_B725F130_47EF_101A_A5F1_02608C9EEBAC_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string _B725F130_47EF_101A_A5F1_02608C9EEBAC_14 {
            get {
                return ResourceManager.GetString("_B725F130_47EF_101A_A5F1_02608C9EEBAC_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Createdate.
        /// </summary>
        internal static string _B725F130_47EF_101A_A5F1_02608C9EEBAC_15 {
            get {
                return ResourceManager.GetString("_B725F130_47EF_101A_A5F1_02608C9EEBAC_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string _B725F130_47EF_101A_A5F1_02608C9EEBAC_20 {
            get {
                return ResourceManager.GetString("_B725F130_47EF_101A_A5F1_02608C9EEBAC_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document manager.
        /// </summary>
        internal static string _D5CDD502_2E9C_101B_9397_08002B2CF9AE_14 {
            get {
                return ResourceManager.GetString("_D5CDD502_2E9C_101B_9397_08002B2CF9AE_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document company.
        /// </summary>
        internal static string _D5CDD502_2E9C_101B_9397_08002B2CF9AE_15 {
            get {
                return ResourceManager.GetString("_D5CDD502_2E9C_101B_9397_08002B2CF9AE_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document category.
        /// </summary>
        internal static string _D5CDD502_2E9C_101B_9397_08002B2CF9AE_2 {
            get {
                return ResourceManager.GetString("_D5CDD502_2E9C_101B_9397_08002B2CF9AE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document presentation format.
        /// </summary>
        internal static string _D5CDD502_2E9C_101B_9397_08002B2CF9AE_3 {
            get {
                return ResourceManager.GetString("_D5CDD502_2E9C_101B_9397_08002B2CF9AE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document slide count.
        /// </summary>
        internal static string _D5CDD502_2E9C_101B_9397_08002B2CF9AE_7 {
            get {
                return ResourceManager.GetString("_D5CDD502_2E9C_101B_9397_08002B2CF9AE_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Anniversary {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_AssistantName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_AssistantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_AssistantTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_AssistantTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment names.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_AttachmentNames {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_AttachmentNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC address.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BccAddress {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BccAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BccName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Birthday {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address city.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressCity {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address country.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressCountry {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address postal code.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressPostalCode {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address post office box.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressPostOfficeBox {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressPostOfficeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address state.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressState {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address street.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressStreet {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business fax number.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessFaxNumber {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_BusinessFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_CallbackTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_CallbackTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_CarTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_CarTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc address.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_CcAddress {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_CcAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_CcName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_CcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Children {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company main telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_CompanyMainTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_CompanyMainTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container hash.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_ContainerHash {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_ContainerHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation ID.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_ConversationID {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_ConversationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taken.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_DateTaken {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display folder.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_DisplayFolder {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_DisplayFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document title prefix.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_DocTitlePrefix {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_DocTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_DueDate {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Duration {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_EmailAddress {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_EmailName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_EmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_EndDate {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FileExt {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension description.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FileExtDesc {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FileExtDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FirstName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag text.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FlagText {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FlagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FolderName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From address.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FromAddress {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FromName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FullName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward or reply.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_FwdRply {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_FwdRply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Gender {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has attachment.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HasAttach {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HasAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Hobby {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address city.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressCity {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address country.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressCountry {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address postalCode.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressPostalCode {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address state.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressState {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address street.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressStreet {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home fax number.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeFaxNumber {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_HomeTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Identity {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM address.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IMAddress {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IMAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Importance {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is attachment.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsAttachment {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is deleted.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsDeleted {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is flagged.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsFlagged {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is flagged completed.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsFlaggedCompleted {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsFlaggedCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is incomplete.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsIncomplete {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is read.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsRead {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is recurring.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsRecurring {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_IsRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_JobTitle {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_LastName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last viewed.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_LastViewed {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_LastViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Location {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_MiddleName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_MobileTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_MobileTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_NickName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Office {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_OfficeTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_OfficeTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_PagerTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_PagerTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_People {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perceived type.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_PerceivedType {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_PerceivedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perceived type name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_PerceivedTypeName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_PerceivedTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal title.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_PersonalTitle {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_PersonalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary date.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_PrimaryDate {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_PrimaryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_PrimaryTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_PrimaryTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Profession {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received date.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_ReceivedDate {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Spouse {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_StartDate {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Store {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_Suffix {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task status.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_TaskStatus {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telex number.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_TelexNumber {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_TelexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To address.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_ToAddress {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_ToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To name.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_ToName {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_ToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTYTDD telephone.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_TTYTDDTelephone {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_TTYTDDTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebPage.
        /// </summary>
        internal static string _D5CDD505_2E9C_101B_9397_08002B2CF9AE_WebPage {
            get {
                return ResourceManager.GetString("_D5CDD505_2E9C_101B_9397_08002B2CF9AE_WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document last printed.
        /// </summary>
        internal static string _F29F85E0_4FF9_1068_AB91_08002B27B3D9_11 {
            get {
                return ResourceManager.GetString("_F29F85E0_4FF9_1068_AB91_08002B27B3D9_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document title.
        /// </summary>
        internal static string _F29F85E0_4FF9_1068_AB91_08002B27B3D9_2 {
            get {
                return ResourceManager.GetString("_F29F85E0_4FF9_1068_AB91_08002B27B3D9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document subject.
        /// </summary>
        internal static string _F29F85E0_4FF9_1068_AB91_08002B27B3D9_3 {
            get {
                return ResourceManager.GetString("_F29F85E0_4FF9_1068_AB91_08002B27B3D9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document author.
        /// </summary>
        internal static string _F29F85E0_4FF9_1068_AB91_08002B27B3D9_4 {
            get {
                return ResourceManager.GetString("_F29F85E0_4FF9_1068_AB91_08002B27B3D9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document keywords.
        /// </summary>
        internal static string _F29F85E0_4FF9_1068_AB91_08002B27B3D9_5 {
            get {
                return ResourceManager.GetString("_F29F85E0_4FF9_1068_AB91_08002B27B3D9_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document comments.
        /// </summary>
        internal static string _F29F85E0_4FF9_1068_AB91_08002B27B3D9_6 {
            get {
                return ResourceManager.GetString("_F29F85E0_4FF9_1068_AB91_08002B27B3D9_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document last author.
        /// </summary>
        internal static string _F29F85E0_4FF9_1068_AB91_08002B27B3D9_8 {
            get {
                return ResourceManager.GetString("_F29F85E0_4FF9_1068_AB91_08002B27B3D9_8", resourceCulture);
            }
        }
    }
}
